name: Build Library

on:
  workflow_dispatch:
    inputs:
      XRAY_VERSION:
        description: "Select Xray-core's version: main (latest commit) or latest (release version)."
        required: true
        type: choice
        default: 'latest'
        options:
        - main
        - latest

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout AndroidLibXrayLite repository
      uses: actions/checkout@main
      with:
        repository: '2dust/AndroidLibXrayLite'
        path: 'AndroidLibXrayLite'

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'
        cache: false

    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Setup Android
      uses: android-actions/setup-android@v2

    - name: Build A Dependency
      run: |
        cd AndroidLibXrayLite
        sed -i "s/v2core.Version())/v2core.Version() + \"${{ env.XRAY_SHA }}\")/" libv2ray_main.go
        go get github.com/xtls/xray-core@${{ inputs.XRAY_VERSION }}
        gomobile init
        go mod tidy -v
        gomobile bind -v -androidapi 21 -ldflags='-s -w' ./

    - name: Push Tag
      id: tag
      run: |
        echo "release_tag=$(date +"%Y%m%d%H%M")" >> $GITHUB_OUTPUT

    - name: Upload Files
      id: release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.FILE_NAME }}
        allowUpdates: true
        tag: ${{ steps.tag.outputs.release_tag }}
        commit: main
        token: ${{ secrets.RELEASES_TOKEN }}
        artifacts: "/AndroidLibXrayLite/libv2ray.aar"
